### ISSUE TITLE
general question ( and thanks, nice stuff )

### ISSUE THREAD

**Issue by x-077** [wacky6/sni-passthrough-backend#1]
Hello, 

I got into SNI / TLS and was looking on how implement such thing, really nice. 

did you improve it maybe :) ? 

Thanks

**Comment by wacky6** [comment]
Glad this is helpful.

I started this "mostly" for fun, when SNI & http2/spdy support in nginx weren't great. Things have improved a lot over the years, and I don't use this tools now (nginx's http2 + X-Forwarded-For solves most of my use cases).

TLS 1.3 starts using encrypted SNI, so the current design probably won't work. 

Not sure what you mean by "did you improve it maybe".

**Comment by x-077** [comment]
Hello @wacky6 , 

I was actually wondering if you may have look at implementing support ESNI. 

It seems that node does not support it (yet) [ESNI as its still in DRAFT](https://github.com/nodejs/node/issues/31618)

it's maybe possible to make it work using [node forge](https://www.npmjs.com/package/node-forge) to handle the crypto part.

I would need to have a closer look at your code and look at [esni-rev-proxy](https://github.com/devopsext/esni-rev-proxy) ( in GO ) to see how they deal with the TLS part.

Fill free to close the thread.

Nice work anyway.

**Comment by wacky6** [comment]
For ESNI, my hunch are:

* Take in a list of ESNI private keys (that are used to decipher encrypted ESNI message)
* When a TLS ClientHello message is received, try all these keys, see if the domain name matches the target
* If yes, connect to backend and pipe the connection; Otherwise close the connection

This would be less scalable (because you need to configure ESNI private keys for every domain).

You would need to make these modifications:
* parse raw TLS ClientHello messages to find ESNI field
* decipher ESNI field using private keys

Good luck.
